### ISSUE TITLE
I am getting an issue defaults undefined

### ISSUE THREAD

**Issue by naveen305** [iominh/ng-scrollbars#11] opened 2015-10-06 12:27 UTC
TypeError: Cannot read property 'defaults' of undefined
    at ScrollBarsDirective.link (directives/scrollBar/scrollbars.js:31:52)

**Comment by iominh** [comment] 2015-10-06 14:59
Hi Naveen,

Thanks for the star and issue. Do you have more details about how I can reproduce that error? If possible, could you create a github repo, possibly by cloning this repo and modifying the basic demo1.html under the gh-pages branch http://iominh.github.io/ng-scrollbars/demo1.html

Minh

**Comment by naveen305** [comment] 2015-10-12 11:18
When i am going from one view to another view and when i  get back again am getting 

TypeError: Cannot read property 'defaults' of undefined
    at ScrollBarsDirective.link (scrollBar/scrollbars.js:31:52)
    at angular.js:7154:44
    at nodeLinkFn (angular.js:6752:13)
    at compositeLinkFn (angular/angular.js:6146:13)
    at compositeLinkFn (angular/angular.js:6149:13)
    at compositeLinkFn (angular/angular.js:6149:13)
    at compositeLinkFn (angular/angular.js:6149:13)
    at compositeLinkFn (angular/angular.js:6149:13)
    at compositeLinkFn (angular/angular.js:6149:13)
    at compositeLinkFn (angular/angular.js:6149:13) <div class="toggleByFading ng-isolate-scope" ng-scrollbars="" ng-scrollbars-config="config">

**Comment by naveen305** [comment] 2015-10-13 12:45
Hi iominh,

Can you update me regarding this issue

**Comment by thillai** [comment] 2015-10-28 09:52
@naveen305 check in console whether jQuery.mCustomScrollbar is defined. Check whether you are reloading jQuery while changing view, which may have removed mCustomScrollbar initialization.

**Comment by iominh** [comment] 2015-10-28 18:47
Thanks Thillai for the reply and my apologies naveen305 for the slow reply -- I've been very busy lately. I'm still not entirely sure how to reproduce the error but from looking at the stack trace, it indeed looks like either jQuery.mCustomScrollbar is undefined (did you include it?) or the ScrollBars module is not defined (did you inject it into your app -- see step 2 in the readme.md)

However, these errors would appear on the initial page load, so I'm not sure why it only appears when you "change views"

**Comment by iominh** [comment] 2015-10-28 18:50
My advice would be to include the non-minified version of ng-scrollbars (scrollbars.js) and set a breakpoint to determine why it's defined in the first view but undefined when you change to another view

**Comment by Mastanka** [comment] 2015-12-13 16:33
I'm experiencing same bug. I found out that the problem is at: 

``` javascript
        // TODO: can we do this without jquery?
        $.mCustomScrollbar.defaults.scrollButtons = this.defaults.scrollButtons;
```

Where "mCustomScrollbar" is undefined.

I've got loaded angular, css and jquery.mCustomScrollbar.concat.min.js and jquery so I dont know what could be the problem. :(

**Comment by iominh** [comment] 2015-12-13 16:44
Hi Mastanka,

Does it load at all or only on a view change? Do the default demos work for you?

Do you mind creating a jsfiddle, codepen, or maybe forking this repo on the [gh-pages branch](https://github.com/iominh/ng-scrollbars/tree/gh-pages) and creating a demo html page (see the [demo1.html](https://github.com/iominh/ng-scrollbars/blob/gh-pages/demo1.html), [demo3.html](https://github.com/iominh/ng-scrollbars/blob/gh-pages/demo3.html) as examples) with your particular includes (like Angular version, jQuery version, etc)?

I'm not sure how to reproduce this issue so any help you can provide would be great.

Thanks!

**Comment by Mastanka** [comment] 2015-12-13 17:11
Hi iominh,
I've created plunker: 
http://plnkr.co/edit/Kk3oaIYpExqeCa1tECmq?p=preview

As you can see div where I'm using directive wont load. (if you delete depenci on ngScrollbars, angular load correctly). But on the second div, where there is pure jQuery scrollbars are loaded correctly. :( It looks like the same problem, but I'm not shure, since I'm new with js/plunker so I cant debug solution any further... 

M.

**Comment by iominh** [comment] 2015-12-14 00:04
Mastanka,

Thanks for putting together that Plunkr. I noticed that your link to ng-scrollbars was set to https://rawgit.com/iominh/ng-scrollbars/blob/src/scrollbars.js, which is invalid? Try https://rawgit.com/iominh/ng-scrollbars/0.0.5/src/scrollbars.js instead. 

Also it didn't look like you were setting up ng-scrollbars correctly. See the following Plunkr: http://plnkr.co/edit/bejvwwzgsDe58HQ1DWjo?p=preview

It shows how to set up your controller and ng-scrollbars on the elements. So check out the html, css, and js

Minh

**Comment by iominh** [comment] 2016-02-05 15:53
Hi all, I'm going to close this ticket, please let me know if you encounter any issues and I'll re-open

**Closed as completed by iominh** 2016-02-05 15:53 UTC

**Comment by N3TC4T** [comment] 2016-05-19 12:40
+1

**Comment by richdho** [comment] 2016-06-01 06:25
I got the same problem. It was because I loaded jquery twice and the app scripts were in the middle. My solution was simplely moving all the app scripts to the bottom.

**Comment by albertkp** [comment] 2018-06-20 09:55
I had the similar issue. It was caused because of loading order in the script tag.  I had the below script which was loaded before ng-scrollbars which caused the issue.
<script src="//cdn.rawgit.com/googlemaps/v3-utility-library/master/markerwithlabel/src/markerwithlabel.js"></script>

Now Iam loading this script after ng-scrollbars have loaded.
